version: '3.3'

services:
  serve:
    build:
      context: .
      dockerfile: ./packages/serve/Dockerfile
    volumes:
      - ./packages/serve:/serve
      - ./dockerNodeModules/serve:/serve/node_modules
    command: bash -c "yarn && yarn dev"
    env_file:
      - ./packages/serve/.env.development
    ports:
      - 3001:3001
    networks:
      - webnet
    depends_on:
      - mongo
  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    volumes:
      - ./packages/web:/web
      - ./dockerNodeModules/web:/web/node_modules
    command: bash -c "yarn && yarn dev"
    ports:
      - 3002:3002
    networks:
      - webnet

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - webnet
    volumes:
      - ./data:/data/db
networks:
  webnet:
