# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build web to github page

on:
  push:
    branches:
      - master
jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '16.x'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PUBLIC_URL: /express-ts/
          envkey_REACT_APP_API_URL: ${{ secrets.URL }}
          directory: packages/web
          file_name: .env
          fail_on_empty: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        id: pnpm-install
        with:
          version: 7.4.0
          run_install: true

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: build
        run: |
          cd packages/web && cat .env && pnpm i && pnpm build && cd ../serve/ && pnpm i && pnpm test

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: packages/web/build
          commit-message: github actions auto commit
          branch: gh-pages
